spring:
  cache:
    type: redis
  redis:
    host: 192.168.254.128
    port: 6500
    jedis:
     pool:
     #负值代表没有限制
       max-active: 8
       max-idle: 8
       min-idle: 0
    password:
    database: 0
server:
  port: 8091

